// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWdeOPccNJfZkWcBx0gwuWHQJ16rlX1Zw',
    appId: '1:861010641092:web:2d66a092ae101b3d208991',
    messagingSenderId: '861010641092',
    projectId: 'notes-10271',
    authDomain: 'notes-10271.firebaseapp.com',
    storageBucket: 'notes-10271.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCehwC-2Kr0qsFuGZwQ8IjXKICJhH5q2k0',
    appId: '1:861010641092:android:b31eda9e7d4abe39208991',
    messagingSenderId: '861010641092',
    projectId: 'notes-10271',
    storageBucket: 'notes-10271.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTTMXPd4amdcZpXRwO8cA2VV3aPZPUWHs',
    appId: '1:861010641092:ios:81e24b8ad857e3f5208991',
    messagingSenderId: '861010641092',
    projectId: 'notes-10271',
    storageBucket: 'notes-10271.appspot.com',
    androidClientId: '861010641092-1pi9ab0jcf2r2ob8d019d00tf85h2dgb.apps.googleusercontent.com',
    iosClientId: '861010641092-go0umkhs7nnasr6eju3jjhm9e249u35o.apps.googleusercontent.com',
    iosBundleId: 'com.example.cashToggarApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTTMXPd4amdcZpXRwO8cA2VV3aPZPUWHs',
    appId: '1:861010641092:ios:81e24b8ad857e3f5208991',
    messagingSenderId: '861010641092',
    projectId: 'notes-10271',
    storageBucket: 'notes-10271.appspot.com',
    androidClientId: '861010641092-1pi9ab0jcf2r2ob8d019d00tf85h2dgb.apps.googleusercontent.com',
    iosClientId: '861010641092-go0umkhs7nnasr6eju3jjhm9e249u35o.apps.googleusercontent.com',
    iosBundleId: 'com.example.cashToggarApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWdeOPccNJfZkWcBx0gwuWHQJ16rlX1Zw',
    appId: '1:861010641092:web:47d378d4fb330cfe208991',
    messagingSenderId: '861010641092',
    projectId: 'notes-10271',
    authDomain: 'notes-10271.firebaseapp.com',
    storageBucket: 'notes-10271.appspot.com',
  );
}
